name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Runs the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'git123'

      - name: Verify Authentication
        run: gcloud auth list

      - name: Check if secrets are set
        run: |
          if [ -z "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" ]; then
            echo "::error::❌ GCP_SERVICE_ACCOUNT_KEY is NOT set!"
            exit 1
          else
            echo "::notice::✅ GCP_SERVICE_ACCOUNT_KEY is set."
          fi

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-service \
            --image=gcr.io/git123/my-image:latest \
            --region=us-central1 \
            --platform=managed
