name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'git123'

      - name: Verify Authentication
        run: gcloud auth list

      - name: Check if secrets are set
        run: |
          if [ -z "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" ]; then
            echo "::error::❌ GCP_WORKLOAD_IDENTITY_PROVIDER is NOT set!"
            exit 1
          else
            echo "::notice::✅ GCP_WORKLOAD_IDENTITY_PROVIDER is set."
          fi

          if [ -z "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" ]; then
            echo "::error::❌ GCP_SERVICE_ACCOUNT_KEY is NOT set!"
            exit 1
          else
            echo "::notice::✅ GCP_SERVICE_ACCOUNT_KEY is set."
          fi
