- name: Authenticate to Google Cloud
  uses: google-github-actions/auth@v1
  with:
    credentials_json: ${{ secrets.GCP_CREDENTIALS }}

- name: Configure Docker for Artifact Registry
  run: |
    gcloud auth configure-docker us-central1-docker.pkg.dev
