jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

- name: Authenticate to Google Cloud
  uses: google-github-actions/auth@v1
  with:
    credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    create_credentials_file: true
    export_environment_variables: true

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'git123'

      - name: Verify Authentication
        run: gcloud auth list
- name: Checkout repository
  uses: actions/checkout@v4
  with:
    submodules: true  # Fetches submodules correctly
