name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify authentication
        run: gcloud auth list

- name: Debug GCP_CREDENTIALS Secret
  run: |
    if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
      echo "GCP_CREDENTIALS secret is empty or not set!"
      exit 1
    else
      echo "GCP_CREDENTIALS is set. Checking JSON format..."
      echo '${{ secrets.GCP_CREDENTIALS }}' | jq .
    fi
