name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          echo '${{ secrets.GCP_CREDENTIALS }}' > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
            --image us-central1-docker.pkg.dev/my-project/my-repo/my-image \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
